projects/rawkode.studio/api/cli/data-migrations/mod.ts, projects/rawkode.studio/api/cli/data-migrations/types.ts, projects/rawkode.studio/api/cli/mod.ts
- some fields in the data model have to be adjusted to reflect the database
=> [feat] introduce "sync" command

projects/rawkode.studio/content-management/cli/docker-compose.yaml, projects/rawkode.studio/content-management/cli/src/command/sync.rs, projects/rawkode.studio/content-management/cli/src/model/people.rs, projects/rawkode.studio/content-management/data/people/myitcv.hcl, projects/rawkode.studio/content-management/data/people/rawkode.hcl
- fix path for migrations
- change model of "person" to have the name as the label
=> [refactor] some things

projects/rawkode.studio/content-management/api/migrations/data/1671035042735_initial/up.sql, projects/rawkode.studio/content-management/cli/.envrc, projects/rawkode.studio/content-management/cli/src/model/technology.rs, projects/rawkode.studio/content-management/cli/src/utils/mod.rs, projects/rawkode.studio/content-management/data/technologies/litmus.hcl, projects/rawkode.studio/content-management/data/technologies/rust.hcl
- Using snake_case for database columsn to remove need for double quotas
- Using .envrc for local development of CLI
- Using block syntax for open_source
- Added additional fields for SEO and YouTube algorithm
Related #27
=> feat: update technology information

projects/rawkode.studio/content-management/api/migrations/data/1671035042735_initial/down.sql, projects/rawkode.studio/content-management/api/migrations/data/1671035042735_initial/up.sql, projects/rawkode.studio/content-management/cli/src/sync/mod.rs, projects/rawkode.studio/content-management/cli/src/utils/mod.rs
=> [feat] remove stale rows

content/klustered/klustered-klustered-teams-container-solutions-civo-cloud.hcl, content/klustered/klustered-klustered-teams-jetstack-crashbeerbackoff.hcl
This PR adds the following episode:
- [Jetstack VS CrashBeerBackOff](https://www.youtube.com/watch?v=Hognhpy3XyA&list=PLz0t90fOInA5IyhoT96WhycPV8Km-WICj)
=> Add new episode 

content/klustered/klustered-klustered-marino-john.hcl
This PR add notes for this [episode](https://www.youtube.com/watch?v=51b2imc6OPM)
=> Add klustered episode

content/klustered/klustered-klustered-leigh-marcus.hcl
This PR adds the notes for this [episode](https://www.youtube.com/watch?v=dr22hR62GXo&t=3708s)
=> Add klustered-klustered-Leigh-Capili-Marcus-Noble

content/episodes/complete-guide-to-spin-go-sdk-walkthrough.hcl, content/episodes/complete-guide-to-spin-nodejs-walkthrough.hcl, content/episodes/complete-guide-to-spin-rust-sdk-walkthrough.hcl, content/episodes/complete-guide-to-spin.hcl
this PR adds notes for the spin walkthrough series
=> add spin walkthroughs

content/episodes/portainer-in-production-part-1.hcl, content/episodes/portainer-in-production-part-2.hcl, content/episodes/portainer-in-production-part-3.hcl
this PR adds not for the portainer in production series
=> Portainer in production

content/episodes/klustered-aerospike-PixieLabs.hcl
This PR adds the PR for the [episode](https://www.youtube.com/watch?v=GHsPEffFLlM)
=> Add klustered-aerospike-PixieLabs.hcl

content/episodes/klustered-klustered-rawkode_null.hcl
This PR add the notes for the [episode](https://www.youtube.com/watch?v=yck5Kr-bwxQ)
=> Add klustered-klustered-rawkode_null.hcl

content/klustered/klustered-polar-signals-pulumi.hcl
This PR adds the notes for this episode [link](https://www.youtube.com/watch?v=jGtR-9SEc1c)
=> Added the new episode of klustered

content/klustered/klustered-skyscanner-digital-ocean.hcl
Add notes for this [episode](https://www.youtube.com/watch?v=JvgpDTx1AZ0)
=> Add klustered-skyscanner-digital-ocean.hcl

projects/rawkode.academy/website/astro.config.mjs, projects/rawkode.academy/website/pnpm-lock.yaml, projects/rawkode.academy/website/src/layouts/mdx-page.astro, projects/rawkode.academy/website/src/pages/how-to-ask-for-help.mdx, projects/rawkode.academy/website/src/pages/pricing._deleted_temp, projects/rawkode.academy/website/src/styles/base.css
The content seems like a good start, it looks like it needs a custom layout though as right now it has no padding or margins so looks bad.
=> asking for help gist converted into a mdx

.gitignore, projects/rawkode.academy/website/src/layouts/mdx-page.astro, projects/rawkode.academy/website/src/pages/index.astro, projects/rawkode.academy/website/src/pages/shows/[key]/index.astro, projects/rawkode.academy/website/src/pages/shows/index.astro, projects/rawkode.academy/website/src/styles/base.css
=> Change MDX page css

projects/rawkode-academy/web/src/pages/blog/[...slug].astro
=> fix:use author name in lieu of Rawkcode Academy

projects/rawkode-academy/web/src/pages/index.astro
Fixes some client side React errors
=> fix(web): use 'client:only="react"'

cdrs/CDR-001-community.md
I assume this change is closer to the intended meaning, but feel free to close if it's not.
=> fix simple typo

projects/rawkode-academy/web/src/pages/about/index.astro
a few simple typo fixes, and adding a full stop to the end of a sentence.
=> fix some simple typos and formatting

projects/rawkode-academy/image-service/LICENSE
- thanks to https://github.com/kvnang/workers-og for the heavy lifting :)
=> chore(image-service): add license file

projects/rawkode-academy/web/src/components/html/head.astro, projects/rawkode-academy/web/src/components/html/opengraph.astro
this is an SEO bump, but also lets screen readers provide a description, so it's an a11y win as well.
=> add meta description and opengraph description

projects/rawkode-academy/web/flake.nix, projects/rawkode-academy/web/src/layouts/app.astro, projects/rawkode-academy/web/src/pages/live.astro
=> feat(web): add /live for live stream player

projects/rawkode-academy/web/src/components/feature/list.vue, projects/rawkode-academy/web/src/pages/index.astro
=> fix(web): use unique icons / emoji for our values

projects/rawkode-academy/web/astro.config.mjs, projects/rawkode-academy/web/src/components/html/opengraph.astro
Tested with `bun run dev` and `bun run build` :)
=> fix(web): set "og:url" depending on DEV / PROD

.github/ISSUE_TEMPLATE/new-defect.yaml
=> feat(github): add a new template for defects

projects/rawkode-academy/web/src/components/html/head.astro, projects/rawkode-academy/web/src/components/html/opengraph.astro, projects/rawkode-academy/web/src/content/blog/zed-show-and-tell.mdx, projects/rawkode-academy/web/src/layouts/app.astro, projects/rawkode-academy/web/src/pages/about/index.astro, projects/rawkode-academy/web/src/pages/blog/[...slug].astro, projects/rawkode-academy/web/src/pages/blog/index.astro, projects/rawkode-academy/web/src/pages/help.astro, projects/rawkode-academy/web/src/pages/index.astro, projects/rawkode-academy/web/src/pages/live.astro, projects/rawkode-academy/web/src/pages/organizations/lets-chat.astro, projects/rawkode-academy/web/src/pages/robots.txt.ts, projects/rawkode-academy/web/src/types/image-service.ts, projects/rawkode-academy/web/src/types/opengraph.ts, projects/rawkode-academy/web/src/wrappers/page.astro, projects/rawkode-academy/web/tsconfig.json
=> Opengraph enhancements

projects/rawkode-academy/web/package.json, projects/rawkode-academy/web/src/pages/404.astro
Closes #201 
**Disclaimer:** It works locally, but I can't say if the custom error page works on Cloudflare.
**Result:**
=> feat(web): add custom 404 page

projects/rawkode-academy/image-service/Justfile, projects/rawkode-academy/image-service/biome.json, projects/rawkode-academy/image-service/package.json, projects/rawkode-academy/image-service/src/lib/fonts.ts, projects/rawkode-academy/image-service/src/lib/template.ts, projects/rawkode-academy/image-service/src/pages/image.ts, projects/rawkode-academy/image-service/src/templates/80s.ts, projects/rawkode-academy/image-service/src/templates/default.ts, projects/rawkode-academy/image-service/src/test/image.test.ts
=> Image service etag

.github/ISSUE_TEMPLATE/new-change.yaml, .github/ISSUE_TEMPLATE/new-defect.yaml, .github/ISSUE_TEMPLATE/new-enhancement.yaml, .github/ISSUE_TEMPLATE/new-operations.yaml
- thanks to @EddieHubCommunity for the idea with the dropdown
- closes #213
=> feat(github): new issue templates

projects/rawkode-academy/web/src/components/calcom/index.tsx, projects/rawkode-academy/web/src/layouts/app.astro, projects/rawkode-academy/web/src/pages/maintainers/share-your-project.astro, projects/rawkode-academy/web/src/pages/organizations/lets-chat.astro
=> feat(web): share your project page

projects/rawkode.academy/documentation/decisions/0001-adopt-madr.md, projects/rawkode.academy/documentation/decisions/0002-service-composition.md, projects/rawkode.academy/documentation/decisions/README.md, projects/rawkode.academy/documentation/decisions/TEMPLATE.md, projects/rawkode.academy/documentation/decisions/deno.json, projects/rawkode.academy/documentation/decisions/deno.lock
=> feat(madr): add initial markdown architectural decision records

projects/rawkode.academy/website/src/components/html/opengraph.astro, projects/rawkode.academy/website/src/pages/blog/[...slug].astro, projects/rawkode.academy/website/src/pages/series/[...slug].astro, projects/rawkode.academy/website/src/types/image-service.ts, projects/rawkode.academy/website/src/types/opengraph.ts
We have to test this one, as I'm using https://docs.astro.build/en/reference/modules/astro-assets/#getimage here
=> feat(website): add article cover to the opengraph image

projects/rawkode.academy/platform/videos/data-model/integrations/zod.ts, projects/rawkode.academy/platform/videos/data-model/migrations/0001_little_sunspot.sql, projects/rawkode.academy/platform/videos/data-model/migrations/meta/0001_snapshot.json, projects/rawkode.academy/platform/videos/data-model/migrations/meta/_journal.json, projects/rawkode.academy/platform/videos/data-model/schema.ts, projects/rawkode.academy/platform/videos/data-model/seed.ts, projects/rawkode.academy/platform/videos/deno.jsonc, projects/rawkode.academy/platform/videos/deno.lock, projects/rawkode.academy/platform/videos/import-from-r2.ts, projects/rawkode.academy/platform/videos/read-model/schema.ts
Supporting `allVideos` was a quick hack to make
things queryable. The website only needs, for now, to fetch the latest videos. So let's default to that.
=> feat(videos): default to `getLatestVideos`

projects/rawkode.academy/website/src/components/hero/typewriter.tsx, projects/rawkode.academy/website/src/components/sidebar/index.vue, projects/rawkode.academy/website/src/components/video/video-feed.astro, projects/rawkode.academy/website/src/pages/index.astro, projects/rawkode.academy/website/src/pages/videos.astro
=> feat(website): integrate latest and random video feed

projects/rawkode.academy/website/src/pages/watch/index.astro
=> fix(website): prerender /watch except random

projects/rawkode.academy/website/src/pages/technology/[id].astro
- Add logging to help debug GraphQL API issues during build
- Add test query with smaller limit before fetching all technologies
- Improve error reporting with full response details
=> feat(rawkode.academy/website): add better error handling for technology GraphQL queries
